#!/usr/bin/env python3
"""Convert the 3D-Craft house dataset into `data.jl`.

3D-Craft (Chen et al., ICCV 2019) ships as a 562 MB tarball of 2,586 houses,
which is far too large to vendor into a Julia package. This script downloads
it, picks a curated subset small enough for a synthesiser to have a chance at,
and emits the Julia source that `Minecraft_Houses_2019` includes.

Usage:

    python3 gen_houses.py --out ../data.jl                    # curated default
    python3 gen_houses.py --out all.jl --max-voxels 100000 --count 2586

The tarball is cached in `--cache` so that re-running is cheap.
"""

import argparse
import json
import os
import tarfile
import urllib.request

DATA_URL = "https://craftassist.s3-us-west-2.amazonaws.com/pubr/house_data.tar.gz"


def download(cache):
    """Fetch the dataset tarball into `cache`, unless it is already there."""
    archive = os.path.join(cache, "house_data.tar.gz")
    if not os.path.exists(archive):
        os.makedirs(cache, exist_ok=True)
        print(f"downloading {DATA_URL} (562 MB) ...")
        urllib.request.urlretrieve(DATA_URL, archive)

    houses = os.path.join(cache, "houses")
    if not os.path.isdir(houses):
        print("extracting ...")
        with tarfile.open(archive) as tar:
            members = [m for m in tar.getmembers() if not m.name.endswith(".png")]
            tar.extractall(cache, members=members)
    return houses


def net_placements(actions):
    """Replay a house's recorded actions into an ordered list of surviving blocks.

    Each action is `[timestamp, player, [x, y, z], [block_id, meta], "P" | "B"]`.
    Breaks ("B") remove a block that a later placement may put back, so the
    house is the *net* result. The order of the survivors is kept, because the
    order blocks go down in is what 3D-Craft is a dataset of.
    """
    placed = {}
    for _, _, (x, y, z), (block_id, _meta), op in actions:
        cell = (x, y, z)
        placed.pop(cell, None)
        if op == "P":
            # Ids above 127 were recorded as signed bytes.
            placed[cell] = block_id if block_id >= 0 else block_id + 256
    return list(placed.items())


def normalise(placements):
    """Translate a house so its lowest corner sits at the origin."""
    if not placements:
        return []
    lo = [min(cell[i] for cell, _ in placements) for i in range(3)]
    return [((x - lo[0], y - lo[1], z - lo[2]), block) for (x, y, z), block in placements]


def load(houses_dir, name):
    path = os.path.join(houses_dir, name, "placed.json")
    if not os.path.exists(path):
        return None
    with open(path) as handle:
        return normalise(net_placements(json.load(handle)))


def select(houses_dir, min_voxels, max_voxels, max_blocks, count):
    """Choose the houses to emit, smallest first.

    Small houses are picked deliberately: the dataset's median house is 528
    blocks, which is not a program anyone is going to synthesise. Capping the
    number of distinct block types keeps the per-house grammars tight too.
    """
    candidates = []
    for name in sorted(os.listdir(houses_dir)):
        placements = load(houses_dir, name)
        if not placements:
            continue
        blocks = {block for _, block in placements}
        if not min_voxels <= len(placements) <= max_voxels:
            continue
        if len(blocks) > max_blocks:
            continue
        candidates.append((len(placements), name, placements))
    candidates.sort(key=lambda c: (c[0], c[1]))
    return candidates[:count]


def emit(selected, out, source_note):
    """Write the Julia source for the selected houses."""
    with open(out, "w") as f:
        f.write('"""\n')
        f.write("The 3D-Craft houses, as ordered block placements.\n\n")
        f.write("GENERATED by `scripts/gen_houses.py` -- do not edit by hand.\n")
        f.write(f"{source_note}\n")
        f.write("\nEach entry is the net result of a human's recorded build, translated so the\n")
        f.write("house's lowest corner is the origin, with the order blocks were laid in\n")
        f.write("preserved. `house_problem` turns one into a `Problem`, a per-house grammar and\n")
        f.write("a reference program that replays the build one block at a time.\n")
        f.write('"""\n\n')

        identifiers = []
        for index, (_, name, placements) in enumerate(selected, start=1):
            identifier = f"house_{index:04d}"
            identifiers.append((identifier, name, len(placements)))
            blocks = sorted({block for _, block in placements})
            dims = [max(cell[i] for cell, _ in placements) + 1 for i in range(3)]

            f.write(f'"""\n    problem_{identifier}\n\n')
            f.write(f"3D-Craft house `{name}`: {len(placements)} blocks in a ")
            f.write(f"{dims[0]}x{dims[1]}x{dims[2]} box, built from {len(blocks)} block ")
            f.write("type" + ("s" if len(blocks) != 1 else "") + ".\n\"\"\"\n")
            f.write(f"const TRACE_{identifier} = [\n")
            for (x, y, z), block in placements:
                f.write(f"    ({x}, {y}, {z}, {block}),\n")
            f.write("]\n\n")
            f.write(f'problem_{identifier}, grammar_{identifier} = ')
            f.write(f'house_problem("{identifier}", TRACE_{identifier})\n\n')

        f.write('"""\n    HOUSE_SOURCES\n\n')
        f.write("Which 3D-Craft house each problem came from, and how many blocks it holds.\n")
        f.write('"""\n')
        f.write("const HOUSE_SOURCES = Dict{String,NamedTuple{(:source, :blocks),Tuple{String,Int}}}(\n")
        for identifier, name, size in identifiers:
            f.write(f'    "{identifier}" => (source = "{name}", blocks = {size}),\n')
        f.write(")\n")
    print(f"wrote {out}: {len(selected)} houses")


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=os.path.join(here, "..", "data.jl"))
    parser.add_argument("--cache", default=os.path.join(here, "cache"))
    parser.add_argument("--min-voxels", type=int, default=25)
    parser.add_argument("--max-voxels", type=int, default=150)
    parser.add_argument("--max-block-types", type=int, default=8)
    parser.add_argument("--count", type=int, default=40)
    args = parser.parse_args()

    houses_dir = download(args.cache)
    selected = select(houses_dir, args.min_voxels, args.max_voxels,
                      args.max_block_types, args.count)
    note = (f"Selection: the {args.count} smallest houses with "
            f"{args.min_voxels}-{args.max_voxels} blocks and at most "
            f"{args.max_block_types} block types.")
    emit(selected, os.path.abspath(args.out), note)


if __name__ == "__main__":
    main()
