"""Differential test of the Julia primitives against z3's SMT-LIB semantics.

Builds a table of (operator, operands, z3's answer) covering random values and
all the corner cases of the theory (0, 1, -1, typemin, typemax, shift distances
around and beyond the width) and emits a Julia script that re-computes every
entry with `hd_primitives.jl` and asserts equality.
"""
import random
import z3

W = 64

UNARY = {
    "bvnot": lambda a: ~a,
    "bvneg": lambda a: -a,
    "bvredor": lambda a: a != 0,
}

BINARY_BV = {
    "bvand": lambda a, b: a & b,
    "bvor": lambda a, b: a | b,
    "bvxor": lambda a, b: a ^ b,
    "bvadd": lambda a, b: a + b,
    "bvsub": lambda a, b: a - b,
    "bvmul": lambda a, b: a * b,
    "bvudiv": z3.UDiv,
    "bvurem": z3.URem,
    "bvsdiv": lambda a, b: a / b,          # z3 maps `/` on BitVec to bvsdiv
    "bvsrem": z3.SRem,
    "bvsmod": lambda a, b: a % b,          # z3 maps `%` on BitVec to bvsmod
    "bvshl": lambda a, b: a << b,
    "bvlshr": z3.LShR,
    "bvashr": lambda a, b: a >> b,         # z3 maps `>>` on BitVec to bvashr
}

BINARY_BOOL = {
    "bvult": z3.ULT,
    "bvule": z3.ULE,
    "bvugt": z3.UGT,
    "bvuge": z3.UGE,
    "bvslt": lambda a, b: a < b,
    "bvsle": lambda a, b: a <= b,
    "bvsgt": lambda a, b: a > b,
    "bvsge": lambda a, b: a >= b,
    "bveq": lambda a, b: a == b,
}

M = 2**W
CORNERS = [0, 1, 2, 3, M - 1, M - 2, M // 2, M // 2 - 1, M // 2 + 1,
           63, 64, 65, 127, 0x5555555555555555, 0xaaaaaaaaaaaaaaaa,
           0xffffffff, 0x100000000, 0x7fffffff, 0x80000000]


def values(rng, n_random=120):
    vals = list(CORNERS)
    for _ in range(n_random):
        vals.append(rng.getrandbits(W))
    # shift-distance-like small values, they exercise the >= width cut-off
    vals += [rng.randrange(0, 130) for _ in range(30)]
    return vals


def ev(expr):
    return z3.simplify(expr)


def main():
    rng = random.Random(4242)
    vals = values(rng)
    lines = []

    for name, fn in UNARY.items():
        for a in vals:
            r = ev(fn(z3.BitVecVal(a, W)))
            if name == "bvredor":
                lines.append('@check %s(0x%016x) === %s' % (name, a, str(z3.is_true(r)).lower()))
            else:
                lines.append('@check %s(0x%016x) === 0x%016x' % (name, a, r.as_long()))

    pairs = [(a, b) for a in CORNERS for b in CORNERS]
    pairs += [(rng.choice(vals), rng.choice(vals)) for _ in range(4000)]
    pairs += [(rng.choice(vals), rng.randrange(0, 130)) for _ in range(1500)]

    for name, fn in BINARY_BV.items():
        for a, b in pairs:
            r = ev(fn(z3.BitVecVal(a, W), z3.BitVecVal(b, W)))
            lines.append('@check %s(0x%016x, 0x%016x) === 0x%016x'
                         % (name, a, b, r.as_long()))

    for name, fn in BINARY_BOOL.items():
        for a, b in pairs:
            r = ev(fn(z3.BitVecVal(a, W), z3.BitVecVal(b, W)))
            lines.append('@check %s(0x%016x, 0x%016x) === %s'
                         % (name, a, b, str(z3.is_true(r)).lower()))

    with open("test_primitives.jl", "w") as f:
        f.write('''# Generated by gen_prim_test.py -- every expected value below was computed by z3.
include("hd_primitives.jl")

const FAILURES = String[]
macro check(ex)
    src = string(ex)
    quote
        try
            $(esc(ex)) || push!(FAILURES, $src)
        catch e
            push!(FAILURES, $src * "  [threw " * string(e) * "]")
        end
    end
end

''')
        f.write("\n".join(lines))
        f.write('''

println("checked ", %d, " cases against z3")
if isempty(FAILURES)
    println("ALL PRIMITIVES MATCH SMT-LIB (z3)")
else
    println(length(FAILURES), " MISMATCHES:")
    for l in first(FAILURES, 40)
        println("  ", l)
    end
    exit(1)
end
''' % len(lines))
    print("wrote test_primitives.jl with %d checks" % len(lines))


if __name__ == "__main__":
    main()
